# Given a ULS correlation id, will return the timestamp associated with that id.
# Some correlation ids are generated by SharePoint server code, in which case they
# are bit-stuffing part of the GUID with timestamp information. However, some
# correlation ids are passed in from client code, and do not have this information.
# Decoding algorithm copied almost verbatim from SPMonitoredScope.cs:CorrelationId(Guid id)
function GetTimestampFromCorrelationId {
    param (
        [guid]$CorrelationId
    )
    
    $bytes = $CorrelationId.ToByteArray()
    if (-not ((($bytes[7] -band 0x0F) -eq 0) -or (($bytes[7] -band 0x0F) -eq 0x0F))) {
        echo "This CorrelationId was not generated on the server, so no timestamp information is available."
        return
    }
    $utcNow = [datetime]::UtcNow
    [long]$lower44BitsMillisecond = ([System.Convert]::ToInt64($bytes[0]) -shl 36) + `
    ([System.Convert]::ToInt64($bytes[1]) -shl 28) + `
    ([System.Convert]::ToInt64($bytes[2]) -shl 20) + `
    ([System.Convert]::ToInt64($bytes[3]) -shl 12) + `
    ([System.Convert]::ToInt64($bytes[4]) -shl 4) + `
    ([System.Convert]::ToInt64($bytes[5]) -shr 4)
    [long]$milliseconds = [long]($utcNow.Ticks / 10000L)
    [long]$lowepart = $milliseconds % (0x1L -shl 44)
    [long]$highpart = $milliseconds - $lowepart
    if ($lowepart -lt $lower44BitsMillisecond) {
        $highpart -= 1
    }
    [long]$ticks = ($highpart + $lower44BitsMillisecond) * 10000L
    [datetime]$timestamp = new-object system.datetime($ticks, [system.datetimekind]::UTC)
    # The bit-stuffing has a bug which may create false positives; try to filter those out here.
    $diff = ($utcNow - $timestamp).TotalDays
    if ($diff -lt 0 -or $diff -gt 3652) {
        echo "This CorrelationId was not generated on the server, so no timestamp information is available."
        return
    }
    elseif ($diff -gt 30) {
        echo "The timestamp indicated is older than 30 days. Logs may no longer be available."
    }
    echo ("Local time: {0}" -f $timestamp.ToLocalTime().ToString("yyyy/MM/dd HH:mm:ss"))
    echo ("UTC time:   {0}" -f $timestamp.ToString("yyyy/MM/dd HH:mm:ssZ"))
}
