//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokenHelper.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SiteUrlSpoCred {
            get {
                return ((string)(this["SiteUrlSpoCred"]));
            }
            set {
                this["SiteUrlSpoCred"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UsernameSpo {
            get {
                return ((string)(this["UsernameSpo"]));
            }
            set {
                this["UsernameSpo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PasswordsSpo {
            get {
                return ((string)(this["PasswordsSpo"]));
            }
            set {
                this["PasswordsSpo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SiteUrlSpoApp {
            get {
                return ((string)(this["SiteUrlSpoApp"]));
            }
            set {
                this["SiteUrlSpoApp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AppIdSpo {
            get {
                return ((string)(this["AppIdSpo"]));
            }
            set {
                this["AppIdSpo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AppSecretSpo {
            get {
                return ((string)(this["AppSecretSpo"]));
            }
            set {
                this["AppSecretSpo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SiteUrlSpoInteractive {
            get {
                return ((string)(this["SiteUrlSpoInteractive"]));
            }
            set {
                this["SiteUrlSpoInteractive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SiteUrlSpCred {
            get {
                return ((string)(this["SiteUrlSpCred"]));
            }
            set {
                this["SiteUrlSpCred"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UsernameSp {
            get {
                return ((string)(this["UsernameSp"]));
            }
            set {
                this["UsernameSp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PasswordsSp {
            get {
                return ((string)(this["PasswordsSp"]));
            }
            set {
                this["PasswordsSp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DomainAdfs {
            get {
                return ((string)(this["DomainAdfs"]));
            }
            set {
                this["DomainAdfs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string StsAdfs {
            get {
                return ((string)(this["StsAdfs"]));
            }
            set {
                this["StsAdfs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string IdpAdfs {
            get {
                return ((string)(this["IdpAdfs"]));
            }
            set {
                this["IdpAdfs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TokenExpAdfs {
            get {
                return ((string)(this["TokenExpAdfs"]));
            }
            set {
                this["TokenExpAdfs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SiteUrlSpApp {
            get {
                return ((string)(this["SiteUrlSpApp"]));
            }
            set {
                this["SiteUrlSpApp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AppIdSp {
            get {
                return ((string)(this["AppIdSp"]));
            }
            set {
                this["AppIdSp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AppSeretSp {
            get {
                return ((string)(this["AppSeretSp"]));
            }
            set {
                this["AppSeretSp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CertificateIssuerIdSp {
            get {
                return ((string)(this["CertificateIssuerIdSp"]));
            }
            set {
                this["CertificateIssuerIdSp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CertificatePathSp {
            get {
                return ((string)(this["CertificatePathSp"]));
            }
            set {
                this["CertificatePathSp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CertificatePasswordsSp {
            get {
                return ((string)(this["CertificatePasswordsSp"]));
            }
            set {
                this["CertificatePasswordsSp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SiteUrlAzureAdCred {
            get {
                return ((string)(this["SiteUrlAzureAdCred"]));
            }
            set {
                this["SiteUrlAzureAdCred"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ClientIdAzureAd {
            get {
                return ((string)(this["ClientIdAzureAd"]));
            }
            set {
                this["ClientIdAzureAd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RedirectUrlAzureAdCred {
            get {
                return ((string)(this["RedirectUrlAzureAdCred"]));
            }
            set {
                this["RedirectUrlAzureAdCred"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SiteUrlAzureAdApp {
            get {
                return ((string)(this["SiteUrlAzureAdApp"]));
            }
            set {
                this["SiteUrlAzureAdApp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TenatAzureAd {
            get {
                return ((string)(this["TenatAzureAd"]));
            }
            set {
                this["TenatAzureAd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AppIdAzureAd {
            get {
                return ((string)(this["AppIdAzureAd"]));
            }
            set {
                this["AppIdAzureAd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RedirectUrlAzureAdApp {
            get {
                return ((string)(this["RedirectUrlAzureAdApp"]));
            }
            set {
                this["RedirectUrlAzureAdApp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CertificatePathAzureAd {
            get {
                return ((string)(this["CertificatePathAzureAd"]));
            }
            set {
                this["CertificatePathAzureAd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CertificatePasswordsAzureAd {
            get {
                return ((string)(this["CertificatePasswordsAzureAd"]));
            }
            set {
                this["CertificatePasswordsAzureAd"] = value;
            }
        }
    }
}
