<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>fc101d3b-033b-495d-813d-3b42f3cdc19b</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MaxMind.GeoIP2" Version="5.3.0" />
    <PackageReference Include="Microsoft.Identity.Client" Version="4.87.0" />
    <PackageReference Include="Microsoft.Identity.Web" Version="4.14.2" />
    <PackageReference Include="Microsoft.Identity.Web.UI" Version="4.14.2" />
  </ItemGroup>

</Project>
